### PR TITLE
A simple minesweeper game-minesweeper[.cpp & .hpp]

### PR DESCRIPTION
**Pull request by Jmallone**
- remove swap() in putrect function;
    graphics.cpp
    It was slowing down the processing.

- Created a basic interface for the keyboard.
    keyboard.cpp
    keyboard.hpp

### CODE REVIEW

**Comment by Kfeavel** [comment]
@Jmallone Since this code doesn't really add any new kernel features (other than the keyboard driver, which I will likely cleanup and merge into `dev`), would you be alight if we added a "demo" section to the `README` with a link to your code? Once we get userspace working (which I will be working on this week, starting finishing the heap code and then allocating user pages), we can absolutely get a finalized version of this added to whatever programs / apps we have as part of the base system. Hopefully by then you could also work on the GUI / windowing code you wanted to do before. 🙂

**Comment by Jmallone** [comment]
@Kfeavel 

Of course, you can put it as "demo" in the `README`
I can't wait for userspace, the GUI will be amazing too

**Comment by Kfeavel** [comment]
We just fixed the kernel heap implementation, so we're going to get that merged and move onto user-space page allocation next. 👍

**Comment by Kfeavel** [comment]
Going to merge the demo section in #385. :+1:

**Pull request closed without merging**
