### PR TITLE
Add macros to check mutex validity and acquire a lock

### LINKED ISSUE #166: Reduce repetitive code and add constants in mutex.cpp
The `mutex.cpp` implementation file has a lot of simple repetitive code.

Two prime examples are:

1. ```c++
    if (mutex == NULL)
    {
        errno = EINVAL;
        return -1;
    }
2. ```c++
    if (__atomic_test_and_set(&mutex->locked, __ATOMIC_RELEASE))
    {
        errno = EINVAL;
        return -1;
    }

Also, throughout the file there are a lot of "magic numbers". There is no reason to use raw `int` return types when we could use something like
```c++
enum class MutexResult {
    success = 0,
    error = -1,
};
```

### PR DESCRIPTION
**Pull request by jamesaorson**
Closes #166

### CODE REVIEW

**Review by Kfeavel — APPROVED** [review]
Looks good to me. Micah loves macros so he'll be happy about this change.

**Review by micahswitzer — APPROVED** [review]
I love it! Can we do the same for the semaphores?

**Comment by jamesaorson** [comment]
> Looks good to me. Micah loves macros so he'll be happy about this change.

Macors are as

> I love it! Can we do the same for the semaphores?

I will add a second commit with the semaphores.

**Review by Kfeavel — APPROVED** [review]
Looks good to me.

**Pull request merged**
