### PR TITLE
Development Merge into Stable - Winter 2020-2021

### PR DESCRIPTION
**Pull request by Kfeavel**
Panix 0.2 Release Candidate

Requirements before merging:

- [x] Tasking with synchronization primitives (#147)
- [x] Stability testing
    - [x] Dynamic memory
    - [x] Tasking
- [x] Global constructors
- [x] Bump version number everywhere necessary

### CODE REVIEW

**Comment by Kfeavel** [comment]
Okay, so we're not going to bump versions in the file headers, but will instead tag the commit as `0.4` and mark it as a release.

**Comment by Kfeavel** [comment]
@micahswitzer wants to have a tasking demo, so we're opting to calculate Pi and display it when complete.

**Review by micahswitzer — APPROVED** [review]
We're go for release!

**Comment by micahswitzer** [comment]
Closing because the WIP bot was blocking our merge.

**Pull request merged**
